version: '2'
services:

    # btc is an image of bitcoin node which used as base image for btcd and
    # btccli. The environment variables default values determined on stage of
    # container start within starting script.
    coind_base:
      image: ${COIN_DAEMON}
      build:
        context: ${COIN_DAEMON}/
      volumes:
            - shared:/rpc
            - blockchain:/data
      environment:
        - RPCUSER
        - RPCPASS
        - NETWORK

    daemon:
        extends: coind_base
        container_name: ${COIN_DAEMON}
        environment:
          - DEBUG
          - MINING_ADDRESS
        entrypoint: ["./start-${COIN_DAEMON}.sh"]

    ctl:
        extends: coind_base
        container_name: ${CTL}
        links:
            - "daemon:rpcserver"
        entrypoint: ["./start-${CTL}.sh"]


    lnd:
        image: lnd
        build:
          context: ../
          dockerfile: docker/lnd/Dockerfile
        environment:
          - RPCUSER
          - RPCPASS
          - NETWORK
          - CHAIN
          - DEBUG
        volumes:
            - shared:/rpc
        entrypoint: ["./start-lnd.sh"]

    alice:
      extends: lnd
      container_name: ${COMPOSE_PROJECT_NAME}_alice
      links:
          - "daemon:blockchain"

    bob:
      extends: lnd
      container_name: ${COMPOSE_PROJECT_NAME}_bob
      links:
          - "daemon:blockchain"

    charlie:
      extends: lnd
      container_name: ${COMPOSE_PROJECT_NAME}_charlie
      links:
          - "daemon:blockchain"

volumes:
  # shared volume is need to store the btcd rpc certificates and us it within
  # btcctl and lnd containers.
  shared:
    driver: local

  # bitcoin volume is needed for maintaining blockchain persistance
  # during btcd container recreation.
  blockchain:
    driver: local
